[project]
name = "daily-bench"
version = "0.1.0"
requires-python = ">=3.9"
description = "Daily benchmarking for LLMs"
authors = [
    { name = "Jacob Phillips", email = "jacob.phillips8905@gmail.com" }
]
dependencies = [
    "lm-eval[api]==0.4.8",
    "pandas",
]

[project.scripts]
daily-bench = "daily_bench.cli:main"

[project.optional-dependencies]
dev = [
  "ruff",
  "pytest",
]

[tool.setuptools.packages.find]
exclude = ["tests*"]
where = ["src"]